# Generated by Django 3.2.4 on 2021-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/service'),
        ),
    ]
